const fs = require("node:fs");
const path = require("node:path");

const root = path.resolve(__dirname, "..", "..");
const batchPath = path.join(root, "prompt_lab", "batches", "martial_visual_concepts_001", "batch_items.json");

const englishPrompts = {
  xiaolin_007_c641b8f2: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style martial arts illustration in a wide horizontal manga-page composition. Arrange several narrow horizontal panels in one image, combining a close foreground palm, a guarded fist, and an intense eye cut-in. Guide the viewer's eye from left to right, with the palm large in the foreground and the face far enough back to remain readable. Use speed lines sparingly, making the order of motion, distance control, and quiet focus easy to understand. Emphasize readable panel rhythm, clean linework, natural cloth folds, balanced anatomy, and a polished manga-action finish.",
  xiaolin_009_1e58c68a: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style martial arts illustration showing sequential motion inside a wooden dojo as manga panels. Stack narrow horizontal panels that show a low stance, the hand just before a palm strike, and a sharp eye cut-in. Use tatami, pillars, and wooden walls as restrained background elements, so the viewer can follow the flow of movement clearly. Focus less on the attack impact itself and more on the tense moment before the technique, the distance between opponents, and the pause of controlled breathing. Keep the panel layout readable, with natural perspective and clear visibility of both expression and hand movement.",
  xiaolin_014_a400315e: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style martial arts illustration set in a bamboo grove, arranged as a manga-panel training sequence. Include a seated breathing cut, a full-body stance cut, a palm-strike hand detail, and a close-up of the eyes within one image. Use vertical bamboo lines to create both stillness and tension. Avoid excessive action effects; instead emphasize the flow from breathing into technique, soft natural light, negative space, and clear eye movement across the panels. Use delicate linework, calm colors, and a readable manga composition.",
  xiaolin_015_2a472ba4: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a polished anime-style illustration of a martial arts girl standing calmly in a bamboo grove. Keep the linework sharp, use restrained greens and whites, and let the bamboo background support the character silhouette without becoming too dense. The pose should remain controlled rather than explosive, showing martial arts through hand placement, weight balance, and natural folds in the clothing. Emphasize clean lines, natural light, balanced anatomy, and a finished illustration style that feels suitable for an article prompt example.",
  xiaolin_016_34893ba8: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style martial arts illustration using shadow and wind trails as the main visual language. Add subtle smoke-like wind flow around the character, and use the contrast between darker shadows and soft natural light to build tension. Keep the movement restrained, emphasizing the stability of the stance and the power held inside the body. Let only the hair and sleeves move slightly, suggesting the moment just before action. Maintain a readable silhouette, sharp linework, and shading that feels dramatic without becoming too heavy.",
  xiaolin_020_554f1a66: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style bust-up portrait in soft bamboo-grove light, emphasizing the eyes. Keep the overall expression calm, while making the eye color, highlights, eyelid shape, and gaze intensity the main focus. Place the bamboo background slightly soft but not completely blurred, and guide natural light toward the eyes. Avoid flashy attack effects; prioritize quiet concentration, a dignified expression, and clear, memorable eyes. Use delicate eye rendering, natural facial shadows, and balanced facial structure.",
  xiaolin_021_ca4807ab: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style close-up portrait from the front, centered on a direct gaze. Carefully render the eye color, highlights, overlap with bangs, and eyelid shape, while keeping the expression restrained. Keep the background simple so the eyes alone communicate focus and quiet strength. Prioritize facial symmetry, natural nose structure, stable eye placement, sharp linework, clear eyes, and a calm sense of tension.",
  xiaolin_022_fc8e9a7d: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style portrait centered on a sharp gaze and shadow falling across the face. Add a controlled shadow around the eyes, using the eyebrow angle and eye highlights to create seriousness. The overall image may be dark, but the eyes must remain clearly readable. Keep the expression emotionally restrained, as if the character is calmly watching for the next move. Emphasize delicate shading, a sharp gaze, natural facial volume, and clean anime-style rendering.",
  xiaolin_023_e884e748: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate an extreme close-up anime-style portrait that boldly crops around the eyes, bangs, and a small part of the nose bridge. Fill the frame with the eye area, carefully rendering eye reflections, eyelashes, hair shadows, and subtle skin shading. Do not show the whole face; express the concentration just before the next motion through the eyes alone. Avoid excessive decoration, using the intensity of the gaze and the tight crop to create impact. Keep the eye anatomy stable and the close-up composition clean.",
  xiaolin_024_2f635a52: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style portrait where most of the face is covered in strong shadow, leaving emotional pressure in the eyes. Use dark shadow, a small glint in the eyes, and a quiet mouth to express inward tension. Do not let the blacks crush the image completely; keep the silhouette, bangs, and cheek volume barely readable. Keep the background restrained so the face shadow and gaze become the main focus. Emphasize heavy but controlled shading, sharp eyes, and stable facial structure.",
  xiaolin_029_51c0c6a2: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style martial arts illustration of a low stance inside a dojo, with a huge wall shadow behind the character. Place the figure slightly small near the lower part of the frame, and make the shadow stretch large across the wall to create psychological pressure. Make the floor, wall, and light source easy to understand, emphasizing the contrast between the small figure and the enormous shadow. Keep the motion minimal, focusing on the presence before releasing a technique and the quiet pressure of the scene. Use a clear light source, strong silhouette, dojo atmosphere, and balanced anatomy.",
  xiaolin_033_f59121cd: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style extreme close-up action illustration where a fist rushes toward the viewer and cracks an invisible screen. Place the fist very large in the foreground, with the face and upper body visible farther back. Use dramatic perspective, glass-like crack lines, speed lines, and white impact shapes, while keeping both the fist and facial expression readable. Do not break the fingers, wrist, or arm structure. Balance impact with clarity, emphasizing strong perspective and a screen-breaking effect.",
  xiaolin_034_b928488a: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style extreme close-up action illustration where the sole of a kicking foot rushes toward the screen and cracks it. Place the sole very large in the foreground, with the face and upper body visible farther back. Use extreme perspective, glass-like crack lines, and speed lines so the force of the kick and the character expression are both clear. Keep the foot shape, leg connection, and body direction anatomically stable. Make the screen-breaking impact the main visual focus with strong depth and a dynamic composition.",
  xiaolin_038_cb2308ed: "Use the reference image as the main guide for the person, outfit, hairstyle, body type, composition, and mood.\n\nPreserve the person, outfit, hairstyle, and body type from the reference image. Only the fixed-character version adds separate character details.\n\nCreate a high-quality anime-style bust-up portrait of the character quietly regulating her breathing in a bamboo grove. Avoid intense motion; show a relaxed shoulder line, soft natural light, and slightly moving hair or fabric to express inner presence. Do not add obvious attack effects. Make the calm moment just before moving from stillness into action the main subject. Arrange the bamboo background gently, so the expression and breathing rhythm are easy to feel. Emphasize soft light, a calm expression, and natural atmosphere.",
};

const englishNegativePrompt = "low quality, broken anatomy, extra fingers, unnatural hands or feet, distorted face, overly asymmetrical eyes, unreadable composition, excessive text, logo, watermark, broken background, major outfit changes, a person who does not match the reference image";

const items = JSON.parse(fs.readFileSync(batchPath, "utf8").replace(/^\uFEFF/, ""));
for (const item of items) {
  if (item.primary === "summary_sheet") {
    item.promptLabel = "設計メモ";
    continue;
  }
  if (!englishPrompts[item.id]) continue;
  item.promptEn = englishPrompts[item.id];
  item.negativeEn = englishNegativePrompt;
  item.promptLabel = "記事用プロンプト";
  item.usageStatus = "article_ready";
}

fs.writeFileSync(batchPath, JSON.stringify(items, null, 2) + "\n", "utf8");

const missing = items.filter((item) => item.primary !== "summary_sheet" && !item.promptEn).map((item) => item.id);
console.log(JSON.stringify({ added: Object.keys(englishPrompts).length, missing }, null, 2));
